// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Shannon Smith

/* Generated by tools/update-translations.py. */
#define N_(text) text

/* metadata.json */
N_("Calendar Plus");
/* metadata.json */
N_("The Cinnamon clock and calendar with multiple time and calendar systems");
/* settings-schema.json:calendar-section */
N_("Calendar systems");
/* settings-schema.json:clock-mode */
N_("Apparent solar time");
/* settings-schema.json:clock-mode */
N_("Binary clock");
/* settings-schema.json:clock-mode */
N_("Choose the time system displayed in the Cinnamon panel.");
/* settings-schema.json:clock-mode */
N_("Clock mode");
/* settings-schema.json:clock-mode */
N_("Decimal time (10-hour day)");
/* settings-schema.json:clock-mode */
N_("Edo Japanese seasonal time");
/* settings-schema.json:clock-mode */
N_("Hexadecimal time (0000 to FFFF)");
/* settings-schema.json:clock-mode */
N_("Internet Time (@000 to @999)");
/* settings-schema.json:clock-mode */
N_("Julian Date");
/* settings-schema.json:clock-mode */
N_("Local mean solar time");
/* settings-schema.json:clock-mode */
N_("Local sidereal time");
/* settings-schema.json:clock-mode */
N_("Modified Julian Date");
/* settings-schema.json:clock-mode */
N_("Roman temporal time");
/* settings-schema.json:clock-mode */
N_("Standard time (12-hour)");
/* settings-schema.json:clock-mode */
N_("Standard time (24-hour)");
/* settings-schema.json:clock-mode */
N_("Standard time (follow Mint setting)");
/* settings-schema.json:clock-mode */
N_("Traditional Chinese double-hours");
/* settings-schema.json:clock-mode */
N_("Unix time (epoch seconds)");
/* settings-schema.json:clock-section */
N_("Clock");
/* settings-schema.json:custom-format */
N_("Date format");
/* settings-schema.json:custom-format */
N_("Set your custom format here.");
/* settings-schema.json:custom-tooltip-format */
N_("Date format for tooltip");
/* settings-schema.json:custom-tooltip-format */
N_("Set your custom tooltip format here.");
/* settings-schema.json:format-button */
N_("Click this button to know more about the syntax for date formats.");
/* settings-schema.json:format-button */
N_("Show information on date format syntax");
/* settings-schema.json:keyOpen */
N_("Set keybinding(s) to show the calendar.");
/* settings-schema.json:keyOpen */
N_("Show calendar");
/* settings-schema.json:latitude */
N_("Latitude in degrees");
/* settings-schema.json:latitude */
N_("Used by Roman temporal and Edo Japanese seasonal time. Enter north latitudes as positive and south latitudes as negative.");
/* settings-schema.json:location-section */
N_("Geographic location");
/* settings-schema.json:longitude */
N_("Longitude in degrees");
/* settings-schema.json:longitude */
N_("Used by local sidereal, solar and location-dependent historical time. Enter east longitudes as positive and west longitudes as negative.");
/* settings-schema.json:primary-calendar */
N_("Bahá’í (Badíʿ)");
/* settings-schema.json:primary-calendar */
N_("Buddhist");
/* settings-schema.json:primary-calendar */
N_("Chinese traditional");
/* settings-schema.json:primary-calendar */
N_("Controls the popup calendar grid, date heading and calendar navigation. Events remain attached to their original dates.");
/* settings-schema.json:primary-calendar */
N_("Coptic");
/* settings-schema.json:primary-calendar */
N_("Ethiopian");
/* settings-schema.json:primary-calendar */
N_("French Republican");
/* settings-schema.json:primary-calendar */
N_("Gregorian");
/* settings-schema.json:primary-calendar */
N_("Hebrew");
/* settings-schema.json:primary-calendar */
N_("ISO week calendar");
/* settings-schema.json:primary-calendar */
N_("Indian National (Saka)");
/* settings-schema.json:primary-calendar */
N_("International Fixed");
/* settings-schema.json:primary-calendar */
N_("Islamic (Umm al-Qura)");
/* settings-schema.json:primary-calendar */
N_("Islamic (astronomical approximation)");
/* settings-schema.json:primary-calendar */
N_("Islamic (civil/tabular)");
/* settings-schema.json:primary-calendar */
N_("Japanese imperial era");
/* settings-schema.json:primary-calendar */
N_("Julian");
/* settings-schema.json:primary-calendar */
N_("Mayan Long Count");
/* settings-schema.json:primary-calendar */
N_("Minguo (Republic of China)");
/* settings-schema.json:primary-calendar */
N_("Persian (Solar Hijri)");
/* settings-schema.json:primary-calendar */
N_("Positivist");
/* settings-schema.json:primary-calendar */
N_("Primary calendar");
/* settings-schema.json:primary-calendar */
N_("Roman");
/* settings-schema.json:primary-calendar */
N_("World Calendar");
/* settings-schema.json:secondary-calendar */
N_("Bahá’í (Badíʿ)");
/* settings-schema.json:secondary-calendar */
N_("Buddhist");
/* settings-schema.json:secondary-calendar */
N_("Chinese traditional");
/* settings-schema.json:secondary-calendar */
N_("Coptic");
/* settings-schema.json:secondary-calendar */
N_("Ethiopian");
/* settings-schema.json:secondary-calendar */
N_("French Republican");
/* settings-schema.json:secondary-calendar */
N_("Gregorian");
/* settings-schema.json:secondary-calendar */
N_("Hebrew");
/* settings-schema.json:secondary-calendar */
N_("ISO week calendar");
/* settings-schema.json:secondary-calendar */
N_("Indian National (Saka)");
/* settings-schema.json:secondary-calendar */
N_("International Fixed");
/* settings-schema.json:secondary-calendar */
N_("Islamic (Umm al-Qura)");
/* settings-schema.json:secondary-calendar */
N_("Islamic (astronomical approximation)");
/* settings-schema.json:secondary-calendar */
N_("Islamic (civil/tabular)");
/* settings-schema.json:secondary-calendar */
N_("Japanese imperial era");
/* settings-schema.json:secondary-calendar */
N_("Julian");
/* settings-schema.json:secondary-calendar */
N_("Mayan Long Count");
/* settings-schema.json:secondary-calendar */
N_("Minguo (Republic of China)");
/* settings-schema.json:secondary-calendar */
N_("None");
/* settings-schema.json:secondary-calendar */
N_("Optionally shows the same day in another calendar beneath the primary date.");
/* settings-schema.json:secondary-calendar */
N_("Persian (Solar Hijri)");
/* settings-schema.json:secondary-calendar */
N_("Positivist");
/* settings-schema.json:secondary-calendar */
N_("Roman");
/* settings-schema.json:secondary-calendar */
N_("Secondary date");
/* settings-schema.json:secondary-calendar */
N_("World Calendar");
/* settings-schema.json:section1 */
N_("Display");
/* settings-schema.json:section2 */
N_("Keyboard shortcuts");
/* settings-schema.json:show-events */
N_("Check this to display events in the calendar.");
/* settings-schema.json:show-events */
N_("Show calendar events");
/* settings-schema.json:show-seconds */
N_("Show seconds");
/* settings-schema.json:show-seconds */
N_("Show seconds or the closest finer unit supported by the selected time system. Modes with fixed historical or epoch precision ignore this setting.");
/* settings-schema.json:show-week-numbers */
N_("Check this to show week numbers in the calendar.");
/* settings-schema.json:show-week-numbers */
N_("Show week numbers in calendar");
/* settings-schema.json:use-custom-format */
N_("Check this to define a custom format for the date in the calendar applet.");
/* settings-schema.json:use-custom-format */
N_("Use a custom date format");
